import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata = {
  title: "PanKri",
  description: "Generated by PanKri",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="mx-3 md:mx-16 lg:mx-32 my-2">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
