import "./globals.css";

export const metadata = {
  title: "PanKri",
  description: "Generated by PanKri",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="mx-5 md:mx-20 lg:mx-36 my-7">{children}</body>
    </html>
  );
}
